parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - local-rules
  - unicorn
extends:
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:unicorn/recommended
env:
  browser: true
  node: true
  es6: true
globals:
  globalThis: readonly

  # Types
  SocketIOClient: readonly
  Console: readonly
rules:
  prettier/prettier:
    - error
    - endOfLine: auto
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/ban-ts-comment': off
  no-dupe-class-members: off
  no-unused-vars: off
  no-redeclare: off
  '@typescript-eslint/no-redeclare': error
  unicorn/filename-case:
    - error
    - cases:
        kebabCase: true
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        args: true
        i: true
        j: true
  unicorn/import-style: off
  unicorn/no-null: off
  unicorn/no-negated-condition: off
  unicorn/no-array-reduce: off
  unicorn/better-regex: off
  unicorn/prefer-ternary: off
  unicorn/no-array-callback-reference: off
  unicorn/no-await-expression-member: off
  unicorn/no-useless-switch-case: off
  unicorn/prefer-at: off
  unicorn/switch-case-braces:
    - error
    - avoid
  unicorn/no-nested-ternary: off
  local-rules/no-unknown-import: error
